export const VOUCHER_LIST_REQUEST = 'VOUCHER_LIST_REQUEST'
export const VOUCHER_LIST_SUCCESS = 'VOUCHER_LIST_SUCCESS'
export const VOUCHER_LIST_FAIL = 'VOUCHER_LIST_FAIL'

export const VOUCHER_DETAILS_REQUEST = 'VOUCHER_DETAILS_REQUEST'
export const VOUCHER_DETAILS_SUCCESS = 'VOUCHER_DETAILS_SUCCESS'
export const VOUCHER_DETAILS_FAIL = 'VOUCHER_DETAILS_FAIL'

export const VOUCHER_DELETE_REQUEST = 'VOUCHER_DELETE_REQUEST'
export const VOUCHER_DELETE_SUCCESS = 'VOUCHER_DELETE_SUCCESS'
export const VOUCHER_DELETE_FAIL = 'VOUCHER_DELETE_FAIL'

export const VOUCHER_CREATE_REQUEST = 'VOUCHER_CREATE_REQUEST'
export const VOUCHER_CREATE_SUCCESS = 'VOUCHER_CREATE_SUCCESS'
export const VOUCHER_CREATE_FAIL = 'VOUCHER_CREATE_FAIL'
export const VOUCHER_CREATE_RESET = 'VOUCHER_CREATE_RESET'

export const VOUCHER_UPDATE_REQUEST = 'VOUCHER_UPDATE_REQUEST'
export const VOUCHER_UPDATE_SUCCESS = 'VOUCHER_UPDATE_SUCCESS'
export const VOUCHER_UPDATE_FAIL = 'VOUCHER_UPDATE_FAIL'
export const VOUCHER_UPDATE_RESET = 'VOUCHER_UPDATE_RESET'